server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000

ribbon:
  ReadTimeout: 500000
  ConnectTimeout: 500000

zuul:
  routes:
    catalog:
      path: /catalog/**
      serviceId: catalog
      stripPrefix: false
      sensitiveHeaders:
    inventory:
      path: /inventory/**
      serviceId: inventory
      stripPrefix: false
      sensitiveHeaders:
    manager:
      path: /manager/**
      serviceId: manager
      stripPrefix: false
      sensetiveHeaders: