server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 70000

ribbon:
  ReadTimeout: 70000
  ConnectTimeout: 70000

zuul:
  routes:
    catalog-service:
      path: /catalog/**
      serviceId: catalog-service
      stripPrefix: false
      sensitiveHeaders:
    inventory-service:
      path: /inventory/**
      serviceId: inventory-service
      stripPrefix: false
      sensitiveHeaders:
    manager-service:
      path: /manager/**
      serviceId: manager
      stripPrefix: false
      sensetiveHeaders: