spring:
  data:
    mongodb:
      host: localhost
      password: 12344321
      port: 27017
      database: inventory
      repositories:
        enabled: true
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/